#!/bin/bash
#Initial network interface configuration
ip link set dev $2 up
dhcpcd $2
ip link set dev $1 up
ip -f inet addr add dev $1 local 172.20.1.1/24
sleep 2		# not sure if this can be lowered to (1) or removed?

#Enable IP forwarding
sysctl -w net.ipv4.ip_forward=1
 
#Start dnsmasq
if [ -z "$(ps -e | grep dnsmasq)" ]
then
systemctl start dnsmasq
fi
 
#Enable NAT
iptables -F
iptables -t nat -F
iptables --delete-chain
iptables -t nat --delete-chain
iptables -t nat -A POSTROUTING -o $2 -j MASQUERADE
iptables -A FORWARD -i $1 -j ACCEPT
iptables -t mangle -N internet
iptables -t mangle -A PREROUTING -i $1 -p tcp -m tcp --dport 80 -j internet
iptables -t mangle -A internet -j MARK --set-mark 99
iptables -t nat -A PREROUTING -i $1 -p tcp -m mark --mark 99 -m tcp --dport 80 -j DNAT --to-destination 172.20.1.1
 
#start hostapd
hostapd /etc/hostapd/hostapd.conf
killall dnsmasq
